### ISSUE TITLE
Is there a place to download your minecraft world code for each video?

### ISSUE THREAD

**Issue by neodan99** [HritikRC/Minecraft#7]
Somewhere between video 9 or ten, my code suddenly doesn't match anymore, and it's off my about 50 lines and I cannot figure it out! Noticed especially in video 10 that maybe some stuff got moved around between videos?

Then on Part 11(Raycasting), it's so different, I tried pulling from the minecraftworld.html file, but that's really different from video 10 too.

Do you happen to have a copy of your world file that's up to date for each video?

Thank you,
- D

**Comment by HritikRC** [comment]
@neodan99

Hey! Sorry for the late reply. Unfortunately, I do not - but GitHub does 8)

If you go to the main page of the repository for the 3D minecraft series (https://github.com/HritikRC/Minecraft) and then you click on the commits, it should say 73 commits, it appears on the right of the date. And then, you should see every edit I made for a file of a certain date. It's a bit of a hassle but I'm afraid this is the only way. Hope this works!

**Comment by neodan99** [comment]
Hey no prob I appreciate your help! Thank you that actually does help, sorry new to github. Now I know about the commit section!
