### ISSUE TITLE
Pressing 'Q' Places multiple blocks

### ISSUE THREAD

**Issue by neodan99** [HritikRC/Minecraft#8]
After video 12 the game is sooo fast. I tried changing the movement speed down a bit which helped.  But still, when tapping 'q' even just for a split second, it places 3-7 blocks. It's like it thinks I'm pressing 'q' longer than I am. Any ideas?

**Comment by HritikRC** [comment]
@neodan99!

Hey! Thanks for your message! That is really strange - are you sure you used the correct code? This should be not be happening. You can try attaching your code and I can try to take a look at it :)

**Comment by neodan99** [comment]
Ok just sent to you, please forgive me github will not allow me to upload html files! One hint to what might be happening, is that I also notice that when I jump, it jumps extremely fast... Thank you

**Comment by d-level** [comment]
Seems like your framerate is higher than @HritikRC's. The shorter the time between frames, the faster the actions execute. You can either change your speed/jump/etc values according to your framerate (e.g. slower speed if fast framerate, higher speed if low framerate), or you can edit the loop function to use a custom framerate, by checking if enough time has passed to update/render the next frame.


```js
import {FRAMES_PER_SECOND} from "./constants.js";
import update from "./update.js";
import render from "./render.js";

export default {
	start: () => {
		currentFrame = currentRealFrame = 0;
		interval = 1000 / FRAMES_PER_SECOND;
		delta = 30 / FRAMES_PER_SECOND;
		then = performance.now();

		counter = counterThen = counterDiff = 0;

		loop();
	},
	stop: () => cancelAnimationFrame(request),
};

let interval, then, now, counter, counterThen, counterDiff, diff, delta, currentFrame, currentRealFrame, request;

function loop() {
	request = requestAnimationFrame(loop);

	counter = now = performance.now();
	diff = now - then;

	counterDiff = counter - counterThen;

	if (currentRealFrame === 0 || diff > interval) {
		then = now - diff % interval;

		currentFrame++;
		currentRealFrame++;

		update(delta);
		render();
	}
}
```
Using this:
```js
import loop from "./loop.js";

// Start the loop using the `FRAMES_PER_SECOND` constant
loop.start();

// ...

// Stop the loop
loop.stop();
```

**Comment by neodan99** [comment]
![placeblock](https://user-images.githubusercontent.com/34558649/216666656-2b5b01a6-f6bd-4e1d-9f41-050fb50e6c71.JPG)
Hey thanks a lot for the advice.  For this solution I would need 4 additional files: loop.js, constants.js, render.js, update.js any tips on where to find those? Then you provided two blocks of code, thank you, not sure where to paste those. It's strange that this issue has not come up before, it's not like I have a super computer. It's good though - 2020 Macbook pro, 16 gb ram, M1 - 8 cores. Tried from my Surface Pro, it's about 4 years old, just another m core type processor, not i5 or i7. Same thing. Here's a screenshot and my fps is normal right? It's totally random how it places, and it's the same for removing blocks as well after I completed video 13. It's usually sort of an "s" shaped pattern, of about 4-5 blocks actually. It's funny how some get placed up in the air, but I think it thinks I'm holding the button. When I run it's so crazy fast, it's hard to control

**Comment by d-level** [comment]
With the image the issue does not seem to come from the framerate. I suggest you to create a repository where you paste your local project and share it here. This way we can replicate the issue :)
The example I provided is just code from a project of mine, its not made for this issue specifically but it shows how it could be implemented.

**Comment by neodan99** [comment]
Hey thanks Matteo! Good idea! 
Ok, added at https://github.com/neodan99/Minecraft-project-part-13 ...if you want to take a look. I added some notes to the readme file with a little more explanation and another screenshot

**Comment by d-level** [comment]
Ive sent a [PR](https://github.com/neodan99/Minecraft-project-part-13/pull/1) with the fix :)

**Comment by neodan99** [comment]
Oh my gosh you are a wizard thank you so much! I spent hours and hours, I don't know how you found that so fast! I really appreciate it!
